// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC58cPLDOaapddLuTjeFOTmWsTfv9zrods',
    appId: '1:711869316490:web:df49afc99502a233c15c73',
    messagingSenderId: '711869316490',
    projectId: 'mood-food-project',
    authDomain: 'mood-food-project.firebaseapp.com',
    storageBucket: 'mood-food-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0jNVYLMOaSXpfESuCqLdRoc0fjyzi1nU',
    appId: '1:711869316490:android:4064f3bfb2acfc7ec15c73',
    messagingSenderId: '711869316490',
    projectId: 'mood-food-project',
    storageBucket: 'mood-food-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVLg3VU90H5p0X1358iOXMAty1RD_VAE0',
    appId: '1:711869316490:ios:7d16c928697de987c15c73',
    messagingSenderId: '711869316490',
    projectId: 'mood-food-project',
    storageBucket: 'mood-food-project.firebasestorage.app',
    iosBundleId: 'com.example.moodFoodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVLg3VU90H5p0X1358iOXMAty1RD_VAE0',
    appId: '1:711869316490:ios:7d16c928697de987c15c73',
    messagingSenderId: '711869316490',
    projectId: 'mood-food-project',
    storageBucket: 'mood-food-project.firebasestorage.app',
    iosBundleId: 'com.example.moodFoodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC58cPLDOaapddLuTjeFOTmWsTfv9zrods',
    appId: '1:711869316490:web:a93aa5531c7254f2c15c73',
    messagingSenderId: '711869316490',
    projectId: 'mood-food-project',
    authDomain: 'mood-food-project.firebaseapp.com',
    storageBucket: 'mood-food-project.firebasestorage.app',
  );
}
